#ifndef LUCIFERON_CONSTANTS_H
#define LUCIFERON_CONSTANTS_H

#define LED_COUNT 74 * 10
#define HEADER_SIZE 4
#define PACKET_SIZE LED_COUNT * 3
#define BAUDRATE 5 * 1000 * 1000
#define LOGGER_NAME "luciferon"
#define COSMOGRAPHER_ENDPOINT "tcp://10.42.0.1:44400"

#endif //LUCIFERON_CONSTANTS_H
